secret_key_base: 0BVG47pMEjIZypgU40LyoGc_t5I9N9aTEncrBtV7ZmI
port: 3000
name: serviceman-api
logging:
  severity: debug
  colorize: true
  filter:
    - password
    - confirm_password
  skip:
    -
  context:
    - request
    - session
    - headers
    - cookies
    - params

host: 0.0.0.0
port_reuse: false
process_count: 1
# ssl_key_file:
# ssl_cert_file:
redis_url: "redis://localhost:6379"
database_url: postgres://postgres:@localhost:5432/serviceman_api_test
session:
  key: amber.session
  store: signed_cookie
  expires: 0
smtp:
  enabled: false

secrets:
  description: Store your development secrets credentials and settings here.


